### ISSUE TITLE
XGBoost example notebook has conflicting numbers of workers

### ISSUE THREAD

**Issue by therriault** [coiled/coiled-examples#5]
In the code, the new cluster is supposed to have 10 workers, but the output describing the cluster shows only 1 worker. See below:

![image](https://user-images.githubusercontent.com/4842513/89820263-c04b1480-db1a-11ea-8123-1dc319856b2c.png)

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @therriault! The client periodically asks the scheduler for an updated list of workers in the cluster, So it's possible for the client to not know about the full set of workers for a short period of time in between workers arriving and the periodic update callback.

Locally, if I move the

```python
client = dask.distributed.Client(cluster)
client
```

lines to a separate cell, that gives enough time for another periodic update call and the full set of workers are listed in the HTML repr.

**Comment by jrbourbeau** [comment]
https://github.com/coiled/coiled-examples/pull/7 moves the client lines to a new notebook cell
